USE [master]
GO

/****** Object:  Database [QLSV]    Script Date: 25/03/2025 19:10:09 ******/
CREATE DATABASE [QLSV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLSV', FILENAME = N'E:\Lap trinh\SQL\QLSV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLSV_log', FILENAME = N'E:\Lap trinh\SQL\QLSV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLSV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLSV] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLSV] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLSV] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLSV] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLSV] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLSV] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLSV] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLSV] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLSV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLSV] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLSV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLSV] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLSV] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLSV] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLSV] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLSV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLSV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLSV] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLSV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLSV] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLSV] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLSV] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLSV] SET RECOVERY FULL 
GO

ALTER DATABASE [QLSV] SET  MULTI_USER 
GO

ALTER DATABASE [QLSV] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLSV] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLSV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLSV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLSV] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLSV] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLSV] SET QUERY_STORE = ON
GO

ALTER DATABASE [QLSV] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [QLSV] SET  READ_WRITE 
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[BoMon]    Script Date: 25/03/2025 19:09:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BoMon](
	[MaBm] [nchar](15) NOT NULL,
	[MaMon] [nchar](15) NULL,
	[MaKhoa] [nchar](15) NULL,
 CONSTRAINT [PK_BoMon] PRIMARY KEY CLUSTERED 
(
	[MaBm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BoMon]  WITH CHECK ADD  CONSTRAINT [FK_BoMon_Khoa] FOREIGN KEY([MaKhoa])
REFERENCES [dbo].[Khoa] ([MaKhoa])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[BoMon] CHECK CONSTRAINT [FK_BoMon_Khoa]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[DKMH]    Script Date: 25/03/2025 20:50:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DKMH](
	[MaLopHP] [nchar](15) NOT NULL,
	[MaSv] [nchar](15) NOT NULL,
	[DiemTP] [float] NULL,
	[DiemThi] [float] NULL,
	[PhanTramThi] [real] NULL,
 CONSTRAINT [PK_DKMH] PRIMARY KEY CLUSTERED 
(
	[MaLopHP] ASC,
	[MaSv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [FK_DKMH_SINHVIEN] FOREIGN KEY([MaLopHP])
REFERENCES [dbo].[LopHP] ([MaLopHP])
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [FK_DKMH_SINHVIEN]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [FK_DKMH_SINHVIEN1] FOREIGN KEY([MaSv])
REFERENCES [dbo].[SINHVIEN] ([MaSv])
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [FK_DKMH_SINHVIEN1]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [CK_DiemTP] CHECK  (([DiemTP]>=(0.0) AND [DiemTP]<=(10.0)))
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [CK_DiemTP]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [CK_DiemThi] CHECK  (([DiemThi]>=(0.0) AND [DiemThi]<=(10.0)))
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [CK_DiemThi]
GO

ALTER TABLE [dbo].[DKMH]  WITH CHECK ADD  CONSTRAINT [CK_PhanTramThi] CHECK  (([PhanTramThi]>=(0) AND [PhanTramThi]<=(100)))
GO

ALTER TABLE [dbo].[DKMH] CHECK CONSTRAINT [CK_PhanTramThi]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'DKMH', @level2type=N'CONSTRAINT',@level2name=N'CK_DiemTP'
GO


USE [QLSV]
GO

/****** Object:  Table [dbo].[GVCN]    Script Date: 25/03/2025 20:50:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GVCN](
	[MaLop] [nchar](15) NOT NULL,
	[MaGv] [nchar](15) NOT NULL,
	[HK] [nchar](10) NULL,
 CONSTRAINT [PK_GVCN_1] PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC,
	[MaGv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD  CONSTRAINT [FK_GVCN_GiaoVien] FOREIGN KEY([MaGv])
REFERENCES [dbo].[GiaoVien] ([MaGv])
GO

ALTER TABLE [dbo].[GVCN] CHECK CONSTRAINT [FK_GVCN_GiaoVien]
GO

ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD  CONSTRAINT [FK_GVCN_LOP] FOREIGN KEY([MaLop])
REFERENCES [dbo].[LOP] ([MaLop])
GO

ALTER TABLE [dbo].[GVCN] CHECK CONSTRAINT [FK_GVCN_LOP]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[GiaoVien]    Script Date: 25/03/2025 20:51:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GiaoVien](
	[MaGv] [nchar](15) NOT NULL,
	[HoTen] [nchar](15) NULL,
	[NgaySinh] [date] NULL,
	[MaBm] [nchar](15) NULL,
 CONSTRAINT [PK_GiaoVien] PRIMARY KEY CLUSTERED 
(
	[MaGv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GiaoVien]  WITH CHECK ADD  CONSTRAINT [FK_GiaoVien_BoMon] FOREIGN KEY([MaBm])
REFERENCES [dbo].[BoMon] ([MaBm])
GO

ALTER TABLE [dbo].[GiaoVien] CHECK CONSTRAINT [FK_GiaoVien_BoMon]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[Khoa]    Script Date: 25/03/2025 20:51:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Khoa](
	[MaKhoa] [nchar](15) NOT NULL,
	[TenKhoa] [nchar](15) NULL,
 CONSTRAINT [PK_Khoa] PRIMARY KEY CLUSTERED 
(
	[MaKhoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Khoa]  WITH CHECK ADD  CONSTRAINT [FK_Khoa_Khoa] FOREIGN KEY([MaKhoa])
REFERENCES [dbo].[Khoa] ([MaKhoa])
GO

ALTER TABLE [dbo].[Khoa] CHECK CONSTRAINT [FK_Khoa_Khoa]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[Khoa]    Script Date: 25/03/2025 20:51:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Khoa](
	[MaKhoa] [nchar](15) NOT NULL,
	[TenKhoa] [nchar](15) NULL,
 CONSTRAINT [PK_Khoa] PRIMARY KEY CLUSTERED 
(
	[MaKhoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Khoa]  WITH CHECK ADD  CONSTRAINT [FK_Khoa_Khoa] FOREIGN KEY([MaKhoa])
REFERENCES [dbo].[Khoa] ([MaKhoa])
GO

ALTER TABLE [dbo].[Khoa] CHECK CONSTRAINT [FK_Khoa_Khoa]
GO


USE [QLSV]
GO

/****** Object:  Table [dbo].[LOP]    Script Date: 25/03/2025 20:51:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LOP](
	[MaLop] [nchar](15) NOT NULL,
	[TenLop] [nchar](15) NULL,
 CONSTRAINT [PK_LOP] PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[LopSV]    Script Date: 25/03/2025 20:53:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LopSV](
	[MaLop] [nchar](15) NOT NULL,
	[MaSv] [nchar](15) NOT NULL,
	[ChucVu] [nchar](15) NULL,
 CONSTRAINT [PK_LopSV] PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC,
	[MaSv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LopSV]  WITH CHECK ADD  CONSTRAINT [FK_LopSV_LopSV] FOREIGN KEY([MaLop])
REFERENCES [dbo].[LOP] ([MaLop])
GO

ALTER TABLE [dbo].[LopSV] CHECK CONSTRAINT [FK_LopSV_LopSV]
GO

ALTER TABLE [dbo].[LopSV]  WITH CHECK ADD  CONSTRAINT [FK_LopSV_SINHVIEN] FOREIGN KEY([MaSv])
REFERENCES [dbo].[SINHVIEN] ([MaSv])
GO

ALTER TABLE [dbo].[LopSV] CHECK CONSTRAINT [FK_LopSV_SINHVIEN]
GO


USE [QLSV]
GO

/****** Object:  Table [dbo].[LopHP]    Script Date: 25/03/2025 20:53:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LopHP](
	[MaLopHP] [nchar](15) NOT NULL,
	[TenLopHP] [nchar](15) NULL,
	[HK] [int] NULL,
	[MaMon] [nchar](15) NULL,
	[MaGv] [nchar](15) NULL,
 CONSTRAINT [PK_LopHP] PRIMARY KEY CLUSTERED 
(
	[MaLopHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_GiaoVien] FOREIGN KEY([MaGv])
REFERENCES [dbo].[GiaoVien] ([MaGv])
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_GiaoVien]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_MonHoc] FOREIGN KEY([MaMon])
REFERENCES [dbo].[MonHoc] ([MaMon])
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_MonHoc]
GO

USE [QLSV]
GO

/****** Object:  Table [dbo].[SINHVIEN]    Script Date: 25/03/2025 20:54:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SINHVIEN](
	[MaSv] [nchar](15) NOT NULL,
	[HoTen] [nchar](15) NULL,
	[NgaySinh] [date] NULL,
 CONSTRAINT [PK_SINHVIEN] PRIMARY KEY CLUSTERED 
(
	[MaSv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SINHVIEN]  WITH CHECK ADD  CONSTRAINT [FK_SINHVIEN_SINHVIEN] FOREIGN KEY([MaSv])
REFERENCES [dbo].[SINHVIEN] ([MaSv])
GO

ALTER TABLE [dbo].[SINHVIEN] CHECK CONSTRAINT [FK_SINHVIEN_SINHVIEN]
GO









